/**
 * The mask codec, checked against fixtures produced by the shipping Python encoder.
 *
 * `rle-fixtures.json` is generated by `editgpt_core.rle.encode`, not written by hand.
 * A decoder tested against my own reading of the format would agree with the reading and
 * not with the bytes, and the format has a trap worth failing on: it is column-major.
 */

import { describe, expect, it } from "vitest";
import fixtures from "./rle-fixtures.json";
import {
  areaPx,
  decodeMask,
  encodeMask,
  maskBounds,
  tintCanvas,
  tintPixels,
  windowAround,
  type MaskPayload,
} from "./rle";

interface Fixture {
  mask: number[][];
  rle: { width: number; height: number; counts: number[] };
}

const cases = fixtures as unknown as Record<string, Fixture>;

function flatten(rows: number[][]): number[] {
  return rows.flat();
}

describe("decodeMask", () => {
  for (const [name, fixture] of Object.entries(cases)) {
    it(`reproduces the '${name}' mask the Python encoder was given`, () => {
      const decoded = decodeMask(fixture.rle);
      expect(Array.from(decoded)).toEqual(flatten(fixture.mask));
    });
  }

  it("does not transpose", () => {
    // The whole reason this test file loads fixtures from Python. A row-major read of a
    // column-major encoding produces a mask that is plausibly object-shaped and wrong,
    // and every square fixture agrees with it.
    const { rle, mask } = cases.tall!;
    expect(rle.width).not.toEqual(rle.height);
    const decoded = decodeMask(rle);
    expect(decoded[1 * rle.width + 0]).toBe(mask[1]![0]);
    expect(decoded[5 * rle.width + 2]).toBe(1);
    expect(decoded[2 * rle.width + 5 - rle.width]).toBeDefined();
  });

  it("returns the right length even for an empty mask", () => {
    const { rle } = cases.empty!;
    expect(decodeMask(rle)).toHaveLength(rle.width * rle.height);
    expect(Array.from(decodeMask(rle)).some((v) => v === 1)).toBe(false);
  });

  it("handles a mask that is set everywhere", () => {
    const { rle } = cases.full!;
    expect(Array.from(decodeMask(rle)).every((v) => v === 1)).toBe(true);
  });
});

describe("areaPx", () => {
  it("agrees with a full decode without doing one", () => {
    for (const fixture of Object.values(cases)) {
      const counted = Array.from(decodeMask(fixture.rle)).reduce((a, b) => a + b, 0);
      expect(areaPx(fixture.rle)).toBe(counted);
    }
  });
});

describe("maskBounds", () => {
  it("frames what SAM selected, not the whole image", () => {
    const { rle } = cases.tall!; // 3x7, bar at column 0 rows 1..3, pixel at (5, 2)
    const box = maskBounds(rle)!;
    expect(box.x0).toBeCloseTo(0 / 3);
    expect(box.x1).toBeCloseTo(3 / 3);
    expect(box.y0).toBeCloseTo(1 / 7);
    expect(box.y1).toBeCloseTo(6 / 7);
  });

  it("is null for an empty mask, so a caller can say 'nothing matched'", () => {
    expect(maskBounds(cases.empty!.rle)).toBeNull();
  });
});

describe("windowAround", () => {
  const aspect = 4 / 3;

  it("keeps a small object framed rather than lost in the picture", () => {
    const tiny = { x0: 0.5, y0: 0.5, x1: 0.52, y1: 0.52 };
    const window = windowAround(tiny, aspect);
    expect(window.x1 - window.x0).toBeLessThan(0.2);
    expect(window.y1 - window.y0).toBeLessThan(0.2);
  });

  it("stays inside the picture for an object against the edge", () => {
    const corner = { x0: 0.0, y0: 0.0, x1: 0.1, y1: 0.1 };
    const window = windowAround(corner, aspect);
    expect(window.x0).toBeGreaterThanOrEqual(0);
    expect(window.y0).toBeGreaterThanOrEqual(0);
    expect(window.x1).toBeLessThanOrEqual(1 + 1e-9);
    expect(window.y1).toBeLessThanOrEqual(1 + 1e-9);
  });

  it("is square in pixels, not in fractions", () => {
    // A ragged row of thumbnails is harder to compare than the objects in it, and
    // equal *fractions* on a non-square image are not equal pixels.
    const box = { x0: 0.4, y0: 0.4, x1: 0.5, y1: 0.5 };
    const window = windowAround(box, aspect);
    const widthPx = (window.x1 - window.x0) * aspect;
    const heightPx = window.y1 - window.y0;
    expect(widthPx).toBeCloseTo(heightPx, 5);
  });

  it("never exceeds the picture even when asked for more context than exists", () => {
    const big = { x0: 0.05, y0: 0.05, x1: 0.95, y1: 0.95 };
    const window = windowAround(big, aspect, 4);
    expect(window.x0).toBeGreaterThanOrEqual(0);
    expect(window.x1).toBeLessThanOrEqual(1 + 1e-9);
  });
});

describe("tintPixels", () => {
  it("paints only the set pixels and leaves the rest transparent", () => {
    const { rle } = cases.tall!;
    const data = tintPixels(rle, [255, 0, 0]);

    const setPixel = (1 * rle.width + 0) * 4;
    const clearPixel = (0 * rle.width + 1) * 4;
    expect(data[setPixel + 3]).toBeGreaterThan(0);
    expect(data[setPixel]).toBe(255);
    expect(data[clearPixel + 3]).toBe(0);
  });

  it("draws the boundary more solidly than the fill", () => {
    // A flat tint turns to mush at thumbnail size, and the boundary is exactly what the
    // user is being asked to compare between candidates.
    const rle = cases.full!.rle; // every pixel set, so the border is the boundary
    const data = tintPixels(rle, [255, 0, 0], 0.4);
    const corner = 0 * 4;
    const middle = (1 * rle.width + 2) * 4;
    expect(data[corner + 3]).toBeGreaterThan(data[middle + 3]!);
  });

  it("is the size of the mask, so the browser does the rescaling", () => {
    const mask: MaskPayload = cases.wide!.rle;
    expect(tintPixels(mask, [0, 128, 255])).toHaveLength(mask.width * mask.height * 4);
  });

  it("leaves a mask with nothing in it entirely transparent", () => {
    const data = tintPixels(cases.empty!.rle, [255, 0, 0]);
    expect(data.every((v) => v === 0)).toBe(true);
  });
});

describe("tintCanvas", () => {
  it("is the size of the mask", () => {
    const mask: MaskPayload = cases.wide!.rle;
    const canvas = tintCanvas(mask, [0, 128, 255]);
    expect([canvas.width, canvas.height]).toEqual([mask.width, mask.height]);
  });
});

describe("encodeMask", () => {
  for (const [name, fixture] of Object.entries(cases)) {
    it(`produces the same bytes Python does for '${name}'`, () => {
      const pixels = Uint8Array.from(fixture.mask.flat());
      const { width, height } = fixture.rle;
      expect(encodeMask(pixels, width, height).counts).toEqual(fixture.rle.counts);
    });
  }

  it("round-trips every fixture", () => {
    for (const fixture of Object.values(cases)) {
      const pixels = decodeMask(fixture.rle);
      const again = encodeMask(pixels, fixture.rle.width, fixture.rle.height);
      expect(Array.from(decodeMask(again))).toEqual(Array.from(pixels));
    }
  });

  it("opens with a zero-length run when the very first pixel is set", () => {
    // The convention that makes odd runs the set ones. Skipping the empty opening run
    // inverts the whole mask, which is the kind of bug that looks like a bad model.
    const pixels = Uint8Array.from([1, 1, 0, 0]);
    expect(encodeMask(pixels, 2, 2).counts[0]).toBe(0);
  });

  it("counts sum to the pixel count, which is what MaskRef validates", () => {
    for (const fixture of Object.values(cases)) {
      const { width, height } = fixture.rle;
      const encoded = encodeMask(decodeMask(fixture.rle), width, height);
      expect(encoded.counts.reduce((a, b) => a + b, 0)).toBe(width * height);
    }
  });
});
